name: Release

on:
  #push:
  #  branches: [ master ]
  #pull_request:
  #  branches: [ master ]

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Package Docker and K8s
        run: |
          sudo apt update -y -qqq
          sudo apt autoremove --purge -y dotnet-apphost-pack-6.0 || true 
          sudo apt autoremove --purge -y dotnet-apphost-pack-7.0 || true 
          sudo apt autoremove --purge -y dotnet-host || true 
          sudo apt autoremove --purge -y dotnet-hostfxr-6.0 || true 
          sudo apt autoremove --purge -y dotnet-hostfxr-7.0 || true 
          sudo apt autoremove --purge -y dotnet-runtime-6.0 || true 
          sudo apt autoremove --purge -y dotnet-runtime-7.0 || true 
          sudo apt autoremove --purge -y dotnet-runtime-deps-6.0 || true 
          sudo apt autoremove --purge -y dotnet-runtime-deps-7.0 || true 
          sudo apt autoremove --purge -y dotnet-sdk-6.0 || true 
          sudo apt autoremove --purge -y dotnet-sdk-7.0 || true 
          sudo apt autoremove --purge -y dotnet-targeting-pack-6.0 || true 
          sudo apt autoremove --purge -y dotnet-targeting-pack-7.0 || true 
          sudo apt autoremove --purge -y google-chrome-stable || true 
          sudo apt autoremove --purge -y google-cloud-sdk || true 
          sudo apt autoremove --purge -y libmono-microsoft-build4.0-cil || true 
          sudo apt autoremove --purge -y libmono-microsoft-build-engine4.0-cil || true 
          sudo apt autoremove --purge -y libmono-microsoft-build-framework4.0-cil || true 
          sudo apt autoremove --purge -y libmono-microsoft-build-tasks-v4.0-4.0-cil || true 
          sudo apt autoremove --purge -y libmono-microsoft-build-utilities-v4.0-4.0-cil || true 
          sudo apt autoremove --purge -y libmono-microsoft-csharp4.0-cil || true 
          sudo apt autoremove --purge -y libmono-microsoft-visualc10.0-cil || true 
          sudo apt autoremove --purge -y libmono-microsoft-web-infrastructure1.0-cil || true 
          sudo apt autoremove --purge -y libmono-sqlite4.0-cil || true 
          sudo apt autoremove --purge -y libmono-system-json-microsoft4.0-cil || true 
          sudo apt autoremove --purge -y libmspack0 || true 
          sudo apt autoremove --purge -y libpq5 || true 
          sudo apt autoremove --purge -y libpq-dev || true 
          sudo apt autoremove --purge -y libsybdb5 || true 
          sudo apt autoremove --purge -y libz3-4 || true 
          sudo apt autoremove --purge -y libz3-dev || true 
          sudo apt autoremove --purge -y microsoft-edge-stable || true 
          sudo apt autoremove --purge -y mono-roslyn || true 
          sudo apt autoremove --purge -y msodbcsql17 || true 
          sudo apt autoremove --purge -y mssql-tools || true 
          sudo apt autoremove --purge -y mysql-client || true 
          sudo apt autoremove --purge -y mysql-client-8.0 || true 
          sudo apt autoremove --purge -y mysql-client-core-8.0 || true 
          sudo apt autoremove --purge -y mysql-common || true 
          sudo apt autoremove --purge -y mysql-server || true 
          sudo apt autoremove --purge -y mysql-server-8.0 || true 
          sudo apt autoremove --purge -y mysql-server-core-8.0 || true 
          sudo apt autoremove --purge -y nginx || true 
          sudo apt autoremove --purge -y nginx-common || true 
          sudo apt autoremove --purge -y packages-microsoft-prod || true 
          sudo apt autoremove --purge -y php8.1-mysql || true 
          sudo apt autoremove --purge -y php8.1-pgsql || true 
          sudo apt autoremove --purge -y php8.1-sqlite3 || true 
          sudo apt autoremove --purge -y postgresql-14 || true 
          sudo apt autoremove --purge -y postgresql-client-14 || true 
          sudo apt autoremove --purge -y postgresql-client-common || true 
          sudo apt autoremove --purge -y postgresql-common || true 
          sudo apt autoremove --purge -y powermgmt-base || true 
          sudo apt autoremove --purge -y powershell || true 
          sudo apt autoremove --purge -y python3-configobj || true 
          sudo apt autoremove --purge -y shim-signed || true 
          sudo apt autoremove --purge -y firefox || true 
          sudo /bin/rm -fr /usr/share/sbt
          sudo /bin/rm -fr /usr/share/gradle*
          sudo /bin/rm -fr /usr/share/miniconda*
          sudo /bin/rm -fr /usr/share/az_*
          sudo /bin/rm -fr /usr/share/swift*
          sudo /bin/rm -fr /usr/share/dotnet*
          sudo /bin/rm -fr /usr/lib/snapd
          sudo /bin/rm -fr /usr/lib/firefox
          sudo /bin/rm -fr /usr/lib/llvm*
          sudo /bin/rm -fr /usr/lib/mono
          sudo /bin/rm -fr /usr/lib/jvm
          sudo /bin/rm -fr /usr/lib/google-cloud-sdk*
          sudo /bin/rm -fr /opt/containerd
          sudo /bin/rm -fr /opt/mssql-tools
          sudo /bin/rm -fr /opt/google
          sudo /bin/rm -fr /opt/pipx
          sudo /bin/rm -fr /opt/az
          sudo /bin/rm -fr /opt/microsoft
          sudo /bin/rm -fr /usr/local/sqlpackage
          sudo /bin/rm -fr /usr/local/n
          sudo /bin/rm -fr /usr/local/aws*
          sudo /bin/rm -fr /usr/local/julia*
          sudo /bin/rm -fr /usr/local/share
          sudo /bin/rm -fr /usr/local/.ghcup
          sudo /bin/rm -fr /opt/hostedtoolcache
          sudo apt install -y -qqq bash wget ca-certificates curl git
          sudo ln -svf bash /bin/sh
          sudo bash scripts/.pre.sh
          sudo apt upgrade -y -qqq
          sudo bash scripts/install_docker.sh
          sudo rm -fr /tmp/.artifacts
          sudo rm -fr /tmp/*
          sudo mkdir /tmp/.artifacts
          sudo bash dl-docker.sh
          sudo mv -f /tmp/*.tar* /tmp/.artifacts/
          sudo bash dl-containerd.sh
          sudo mv -f /tmp/*.tar* /tmp/.artifacts/
          sudo bash dl-docker-only.sh
          sudo mv -f /tmp/*.tar* /tmp/.artifacts/
          sudo bash dl-etcd.sh
          sudo mv -f /tmp/*.tar* /tmp/.artifacts/
          sudo bash dl-flanneld.sh
          sudo mv -f /tmp/*.tar* /tmp/.artifacts/
          
          #sudo bash dl-k8s.sh "1.23.10"
          #sudo mv -f /tmp/*.tar* /tmp/.artifacts/
          
          #sudo bash dl-k8s.sh "1.24.4"
          #sudo mv -f /tmp/*.tar* /tmp/.artifacts/
          
          #sudo bash dl-k8s.sh "1.25.6"
          #sudo mv -f /tmp/*.tar* /tmp/.artifacts/

          sudo bash dl-k8s.sh "1.29.5"
          sudo mv -f /tmp/*.tar* /tmp/.artifacts/

          sudo bash dl-k8s.sh "1.30.1"
          sudo mv -f /tmp/*.tar* /tmp/.artifacts/

          sudo sleep 2
          sudo chmod 0644 /tmp/.artifacts/*.tar*
          exit

      - name: Update files
        run: |
          _dateutc=$(date -u +%Y-%m-%d)
          _repo="$(echo ${{ github.repository }} | awk -F '/' '{print $2}')"
          ls -1 /tmp/.artifacts/*.tar.xz 2>/dev/null | xargs -I "{}" sudo bash scripts/.upload_file_to_github-release.sh --token ${{ secrets.GITHUB_TOKEN }} --user "${{ github.repository_owner }}" --repo "${_repo}" --file "{}" --tag "v${_dateutc}"
          ls -1 /tmp/.artifacts/*.tar.xz.sha256 2>/dev/null | xargs -I "{}" sudo bash scripts/.upload_file_to_github-release.sh --token ${{ secrets.GITHUB_TOKEN }} --user "${{ github.repository_owner }}" --repo "${_repo}" --file "{}" --tag "v${_dateutc}"
          sudo sleep 2
          cd /tmp
          sudo rm -fr /tmp/.artifacts
          sudo rm -fr /tmp/*
          exit

