name: Release

on:
  #push:
  #  branches: [ master ]
  #pull_request:
  #  branches: [ master ]

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Install docker
        run: |
          sudo apt update -y -qqq
          sudo apt autoremove --purge -y needrestart || true
          sudo apt install -y bash wget
          sudo ln -svf bash /bin/sh
          sudo bash scripts/clean-os.sh
          sudo apt upgrade -y -qqq
          sudo bash scripts/install-docker.sh

      - name: Generate release tag env
        run: |
          _release_ver="v$(date -u +%Y-%m-%d)"
          echo "_release_ver=${_release_ver}" >> $GITHUB_ENV

      - name: Package K8s 1.31
        run: |
          #sudo bash dl-etcd.sh
          #sudo mv -f /tmp/*.tar* /tmp/.artifacts/
          #sudo bash dl-flanneld.sh
          #sudo mv -f /tmp/*.tar* /tmp/.artifacts/
          sudo /bin/rm -fr /tmp/.artifacts
          sudo /bin/rm -fr /tmp/*
          sudo mkdir /tmp/.artifacts
          sudo bash dl-k8s.sh "1.31.2"
          sudo mv -f /tmp/*.tar* /tmp/.artifacts/
          sudo chmod 0644 /tmp/.artifacts/*.tar*
      - name: Upload files
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env._release_ver }}
          files: /tmp/.artifacts/*.tar*

      #- name: Package K8s 1.30
      #  run: |
      #    sudo /bin/rm -fr /tmp/.artifacts
      #    sudo /bin/rm -fr /tmp/*
      #    sudo mkdir /tmp/.artifacts
      #    sudo bash dl-k8s.sh "1.30.6"
      #    sudo mv -f /tmp/*.tar* /tmp/.artifacts/
      #    sudo chmod 0644 /tmp/.artifacts/*.tar*
      #- name: Upload files
      #  uses: softprops/action-gh-release@v2
      #  with:
      #    tag_name: ${{ env._release_ver }}
      #    files: /tmp/.artifacts/*.tar*

      - name: Delete old release tag env
        run: |
          sed -e "/^_release_ver=/d" -i $GITHUB_ENV
